---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/Rendering
    about: Read the documentation for Rendering
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/Rendering/discussions
    about: Ask questions and discuss with the community
