// <copyright file="GalleryIndex.cs" company="DemaConsulting">
// Copyright (c) DemaConsulting. All rights reserved.
// </copyright>

using System.Linq;
using System.Text;

namespace DemaConsulting.Rendering.Gallery;

/// <summary>
///     Generates the browsable <c>README.md</c> pages from the <see cref="GalleryCatalog"/>: a short
///     top-level index (<c>docs/gallery/README.md</c>) linking to one full page per topology-based group
///     (<c>docs/gallery/&lt;group&gt;/README.md</c>). The output is kept markdownlint-clean (blank-line-
///     separated headings and paragraphs, lines wrapped to 120 columns, alt text on every image) so the
///     committed pages pass the repository's lint gate.
/// </summary>
internal static class GalleryIndex
{
    /// <summary>Maximum line length permitted by the repository markdownlint configuration (MD013).</summary>
    private const int MaxLineLength = 120;

    /// <summary>Builds the short, marketing-style top-level <c>README.md</c> index from the catalog.</summary>
    /// <returns>The complete top-level <c>README.md</c> document, ending with a single newline.</returns>
    public static string BuildTopIndex()
    {
        var builder = new StringBuilder();

        AppendParagraph(builder, "# Rendering Gallery");
        AppendParagraph(
            builder,
            "See what the Rendering library can do with your own data. Every image below is "
            + "generated by the gallery test project directly from the public API — this page "
            + "doubles as an end-to-end rendering smoke test, not a set of hand-drawn mock-ups. "
            + "Regenerate every page and image by running `./gallery.ps1` from the repository root.");
        AppendParagraph(
            builder,
            "Bring a graph shaped like yours and find its group below: each one takes the *same kind* "
            + "of input data and lays it out with several of the bundled algorithms side by side, so "
            + "you can see whether the automatic `auto` choice looks right for your case or whether "
            + "you'd rather call a specific algorithm directly. The one exception is **Appearance and "
            + "themes**, which is grouped by visual capability instead of input shape. **Layout "
            + "regressions** is kept separate too, as a permanent record of bugs that were fixed and "
            + "must stay fixed.");
        AppendParagraph(
            builder,
            "Each group's own page has the full diagram set with detailed captions explaining what "
            + "each one demonstrates and, where relevant, which bug it guards against. This page just "
            + "points the way and shows a taste of each.");

        // Written directly (not via AppendParagraph) so the header and separator rows are not
        // blank-line-separated from each other or from the data rows: a Markdown table is one
        // contiguous block, and a blank line between its rows would break it into separate tables.
        builder.Append("| Group | What it's about |").Append('\n');
        builder.Append("| --- | --- |").Append('\n');
        foreach (var group in GalleryCatalog.Groups)
        {
            builder
                .Append($"| [{group.Title}]({group.Folder}/README.md) | {group.ShortSummary} |")
                .Append('\n');
        }

        builder.Append('\n');

        AppendParagraph(builder, "## A taste of what's inside");

        var highlights = GalleryCatalog.Groups
            .SelectMany(group => group.Sections
                .SelectMany(section => section.Images)
                .Where(image => image.IsTopIndexHighlight)
                .Select(image => (group, image)));
        foreach (var (group, image) in highlights)
        {
            var fileName = Path.GetFileName(image.FileName);
            AppendParagraph(builder, $"![{image.Alt}]({group.Folder}/{fileName})");
            AppendParagraph(
                builder,
                $"{image.Caption} See [{group.Title}]({group.Folder}/README.md) for the full set.");
        }

        // Collapse the trailing paragraph separator to a single terminating newline (MD047).
        return builder.ToString().TrimEnd('\n') + "\n";
    }

    /// <summary>Builds one group's full <c>README.md</c> page text from its sections.</summary>
    /// <param name="group">The group to render.</param>
    /// <returns>The complete group <c>README.md</c> document, ending with a single newline.</returns>
    public static string BuildGroupPage(GalleryGroup group)
    {
        var builder = new StringBuilder();

        AppendParagraph(builder, $"# {group.Title}");
        AppendParagraph(builder, group.Intro);
        AppendParagraph(builder, "[Back to the gallery index](../README.md)");

        foreach (var section in group.Sections)
        {
            AppendParagraph(builder, $"## {section.Title}");
            AppendParagraph(builder, section.Intro);

            foreach (var image in section.Images)
            {
                // Images live alongside this page's own README.md, so link by basename only.
                AppendParagraph(builder, $"![{image.Alt}]({Path.GetFileName(image.FileName)})");
                AppendParagraph(builder, image.Caption);
            }
        }

        // Collapse the trailing paragraph separator to a single terminating newline (MD047).
        return builder.ToString().TrimEnd('\n') + "\n";
    }

    /// <summary>
    ///     Writes the top-level index and every group page under <paramref name="rootDirectory"/>,
    ///     creating each group's subfolder as needed.
    /// </summary>
    /// <param name="rootDirectory">The gallery root directory (for example <c>docs/gallery</c>).</param>
    /// <returns>The absolute paths of every written <c>README.md</c> file, top-level index first.</returns>
    public static IReadOnlyList<string> WriteAll(string rootDirectory)
    {
        var encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        var written = new List<string>();

        var topIndexPath = Path.Combine(rootDirectory, "README.md");
        File.WriteAllText(topIndexPath, BuildTopIndex(), encoding);
        written.Add(topIndexPath);

        foreach (var group in GalleryCatalog.Groups)
        {
            var groupDirectory = Path.Combine(rootDirectory, group.Folder);
            Directory.CreateDirectory(groupDirectory);

            var groupPath = Path.Combine(groupDirectory, "README.md");
            File.WriteAllText(groupPath, BuildGroupPage(group), encoding);
            written.Add(groupPath);
        }

        return written;
    }

    /// <summary>
    ///     Appends a paragraph — its text word-wrapped to <see cref="MaxLineLength"/> — followed by a
    ///     blank separator line, so headings and paragraphs are always blank-line separated.
    /// </summary>
    private static void AppendParagraph(StringBuilder builder, string text)
    {
        foreach (var line in WrapToWidth(text, MaxLineLength))
        {
            builder.Append(line).Append('\n');
        }

        builder.Append('\n');
    }

    /// <summary>
    ///     Greedily wraps <paramref name="text"/> on word boundaries so no line exceeds
    ///     <paramref name="width"/> columns. A single word longer than the width is emitted on its own
    ///     line rather than broken.
    /// </summary>
    private static IEnumerable<string> WrapToWidth(string text, int width)
    {
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var line = new StringBuilder();

        foreach (var word in words)
        {
            if (line.Length == 0)
            {
                line.Append(word);
            }
            else if (line.Length + 1 + word.Length <= width)
            {
                line.Append(' ').Append(word);
            }
            else
            {
                yield return line.ToString();
                line.Clear();
                line.Append(word);
            }
        }

        if (line.Length > 0)
        {
            yield return line.ToString();
        }
    }
}
